name = input("Please enter your name: ")
major = input("Please enter your major: ")
interest = input("Please enter your technology interest: ")
skill_goal = input("Please enter your skill goal: ")
print(f"\n\n\tSenior Project Developer Profile\nName: {name}\nMajor: {major}\nTechnology Interest: {interest}\nSkill Goal: {skill_goal}")
